ahoyapi: v2

entrypoint:
  - zsh
  - "-c"
  - '{{cmd}}'
  - '{{name}}'

commands:
  build:
    cmd: ./gradlew build
    usage: Compile java sources

  hello:
    cmd: ./gradlew run --args="$*"
    usage: Run the Hello program

  test:
    cmd: ./gradlew test
    usage: Run HelloTest

  coverage:
    cmd: |
      ./gradlew test
      open app/build/reports/jacoco/test/html/index.html
