ahoyapi: v2

entrypoint:
  - zsh
  - "-c"
  - '{{cmd}}'
  - '{{name}}'

commands:
  build:
    cmd: javac -d bin -g -cp lib/junit-platform-console-standalone-1.9.2.jar src/**/*
    usage: Compile java sources in the `src` directory

  hello:
    cmd: java -cp bin Hello $*
    usage: Run the Hello program

  test:
    cmd: |
      java \
        -javaagent:/Users/nathan.wells/.vscode/jacocoagent.jar=destfile=target/jacoco.exec,append=false \
        -jar lib/junit-platform-console-standalone-1.9.2.jar \
        --class-path bin \
        --scan-class-path
    usage: Run HelloTest

  coverage-report:
    cmd: |
      java \
        -jar lib/jacococli.jar \
        report \
        target/jacoco.exec \
        --classfiles bin \
        --sourcefiles src \
        --html target/coverage-report
