/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nwwells.java_hello;

import javax.annotation.processing.Generated;

public class App {

    @Generated("")
    public static void main(final String[] args) throws Exception {
        final Hello hello = new Hello(args);
        System.out.println(hello);
    }
}
